-- Product usage + engagement tracking (service-role only)
-- Safe to re-run.

create table if not exists public.api_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  action text not null
    check (action in (
      'ocr_ok',
      'ocr_error',
      'ocr_rate_limit',
      'books_ok',
      'books_rate_limit'
    )),
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists api_usage_events_action_created_idx
  on public.api_usage_events (action, created_at desc);

create index if not exists api_usage_events_user_created_idx
  on public.api_usage_events (user_id, created_at desc);

create table if not exists public.user_engagement (
  user_id uuid primary key references auth.users (id) on delete cascade,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  request_count bigint not null default 1
);

create index if not exists user_engagement_last_seen_idx
  on public.user_engagement (last_seen_at desc);

alter table public.api_usage_events enable row level security;
alter table public.user_engagement enable row level security;

revoke all on public.api_usage_events from anon, authenticated;
revoke all on public.user_engagement from anon, authenticated;

grant select, insert on public.api_usage_events to service_role;
grant select, insert, update on public.user_engagement to service_role;
grant usage, select on all sequences in schema public to service_role;
