-- Admin audit log (service-role only; no client grants)
-- Safe to re-run.

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users (id) on delete set null,
  action text not null,
  target_user_id uuid references auth.users (id) on delete set null,
  meta jsonb not null default '{}'::jsonb,
  ip text,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log (created_at desc);

create index if not exists admin_audit_log_actor_idx
  on public.admin_audit_log (actor_user_id);

create index if not exists admin_audit_log_target_idx
  on public.admin_audit_log (target_user_id);

alter table public.admin_audit_log enable row level security;

-- No policies for anon/authenticated — deny by default under RLS.
revoke all on public.admin_audit_log from anon, authenticated;
grant select, insert on public.admin_audit_log to service_role;
