-- ShelfMapper — migrate an existing (close) Supabase database
-- Safe to re-run. Adds missing tables/columns/indexes/RLS/storage.
-- Does not drop leftover columns (e.g. image_hash, cover_url after copy).

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

create or replace function public.hilibrary_has_column(tbl text, col text)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = tbl
      and column_name = col
  );
$$;

-- ---------------------------------------------------------------------------
-- Tables (create only if missing)
-- ---------------------------------------------------------------------------

create table if not exists public.libraries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  name text,
  created_at timestamptz default now()
);

create table if not exists public.shelves (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  library_id bigint,
  name text,
  image_url text not null,
  detected_spines jsonb,
  dismissed_titles jsonb,
  map_x double precision,
  map_y double precision,
  map_scale double precision,
  created_at timestamptz default now(),
  map_width integer
);

create table if not exists public.user_books (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  shelf_id bigint,
  title text,
  author text,
  cover text,
  shelf_image_url text,
  bounding_box jsonb,
  polygon jsonb,
  created_at timestamptz default now()
);

create table if not exists public.ocr_cache (
  hash text primary key,
  words jsonb not null default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.library_shares (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  library_id bigint references public.libraries (id) on delete cascade,
  token text not null unique,
  created_at timestamptz default now(),
  revoked_at timestamptz
);

-- ---------------------------------------------------------------------------
-- shelves: add missing columns used by the app
-- ---------------------------------------------------------------------------

alter table public.shelves add column if not exists user_id uuid;
alter table public.shelves add column if not exists library_id bigint;
alter table public.shelves add column if not exists name text;
alter table public.shelves add column if not exists image_url text;
alter table public.shelves add column if not exists detected_spines jsonb;
alter table public.shelves add column if not exists dismissed_titles jsonb;
alter table public.shelves add column if not exists map_x double precision;
alter table public.shelves add column if not exists map_y double precision;
alter table public.shelves add column if not exists map_scale double precision;
alter table public.shelves add column if not exists created_at timestamptz default now();
alter table public.shelves add column if not exists map_width integer;

-- ---------------------------------------------------------------------------
-- user_books: cover_url -> cover, then add remaining columns
-- ---------------------------------------------------------------------------

do $$
begin
  if public.hilibrary_has_column('user_books', 'cover_url')
     and not public.hilibrary_has_column('user_books', 'cover') then
    alter table public.user_books rename column cover_url to cover;
  elsif public.hilibrary_has_column('user_books', 'cover_url')
        and public.hilibrary_has_column('user_books', 'cover') then
    update public.user_books
    set cover = cover_url
    where cover is null and cover_url is not null;
  end if;
end $$;

alter table public.user_books add column if not exists user_id uuid;
alter table public.user_books add column if not exists shelf_id bigint;
alter table public.user_books add column if not exists title text;
alter table public.user_books add column if not exists author text;
alter table public.user_books add column if not exists cover text;
alter table public.user_books add column if not exists shelf_image_url text;
alter table public.user_books add column if not exists bounding_box jsonb;
alter table public.user_books add column if not exists polygon jsonb;
alter table public.user_books add column if not exists created_at timestamptz default now();

alter table public.ocr_cache add column if not exists words jsonb;
alter table public.ocr_cache add column if not exists created_at timestamptz default now();
alter table public.library_shares add column if not exists user_id uuid;
alter table public.library_shares add column if not exists library_id bigint;
alter table public.library_shares add column if not exists token text;
alter table public.library_shares add column if not exists created_at timestamptz default now();
alter table public.library_shares add column if not exists revoked_at timestamptz;
alter table public.libraries add column if not exists user_id uuid;
alter table public.libraries add column if not exists name text;
alter table public.libraries add column if not exists created_at timestamptz default now();

-- ---------------------------------------------------------------------------
-- Constraints / FKs (skip if they already exist)
-- ---------------------------------------------------------------------------

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'shelves_user_id_fkey'
  ) then
    alter table public.shelves
      add constraint shelves_user_id_fkey
      foreign key (user_id) references auth.users (id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'shelves_library_id_fkey'
  ) then
    alter table public.shelves
      add constraint shelves_library_id_fkey
      foreign key (library_id) references public.libraries (id) on delete set null;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'user_books_user_id_fkey'
  ) then
    alter table public.user_books
      add constraint user_books_user_id_fkey
      foreign key (user_id) references auth.users (id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'user_books_shelf_id_fkey'
  ) then
    alter table public.user_books
      add constraint user_books_shelf_id_fkey
      foreign key (shelf_id) references public.shelves (id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'libraries_user_id_fkey'
  ) then
    alter table public.libraries
      add constraint libraries_user_id_fkey
      foreign key (user_id) references auth.users (id) on delete cascade;
  end if;
end $$;

-- Unique image_url (required by the app). Fails if duplicates already exist.
create unique index if not exists shelves_image_url_key on public.shelves (image_url);

create index if not exists libraries_user_id_idx on public.libraries (user_id);
create index if not exists shelves_user_id_idx on public.shelves (user_id);
create index if not exists shelves_library_id_idx on public.shelves (library_id);
create index if not exists user_books_user_id_idx on public.user_books (user_id);
create index if not exists user_books_shelf_id_idx on public.user_books (shelf_id);
create index if not exists library_shares_user_id_idx on public.library_shares (user_id);
create unique index if not exists library_shares_token_key on public.library_shares (token);

-- ---------------------------------------------------------------------------
-- Grants + RLS
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated, service_role;

grant select, insert, update, delete
  on public.libraries, public.shelves, public.user_books, public.library_shares
  to authenticated;

grant all on public.libraries, public.shelves, public.user_books, public.ocr_cache, public.library_shares
  to service_role;

revoke all on public.ocr_cache from anon, authenticated;

grant usage, select
  on all sequences in schema public
  to authenticated, service_role;

alter table public.libraries enable row level security;
alter table public.shelves enable row level security;
alter table public.user_books enable row level security;
alter table public.ocr_cache enable row level security;
alter table public.library_shares enable row level security;

drop policy if exists libraries_own_rows on public.libraries;
create policy libraries_own_rows
  on public.libraries
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists shelves_own_rows on public.shelves;
create policy shelves_own_rows
  on public.shelves
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists user_books_own_rows on public.user_books;
create policy user_books_own_rows
  on public.user_books
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and (
      shelf_id is null
      or exists (
        select 1
        from public.shelves s
        where s.id = shelf_id
          and s.user_id = auth.uid()
      )
    )
  );

drop policy if exists library_shares_own_rows on public.library_shares;
create policy library_shares_own_rows
  on public.library_shares
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and (
      library_id is null
      or exists (
        select 1
        from public.libraries l
        where l.id = library_id
          and l.user_id = auth.uid()
      )
    )
  );

-- ---------------------------------------------------------------------------
-- Storage bucket
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('shelves', 'shelves', false)
on conflict (id) do update
set public = false;

drop policy if exists "Public read shelf images" on storage.objects;
drop policy if exists "Users read own shelf images" on storage.objects;
create policy "Users read own shelf images"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users upload own shelf images" on storage.objects;
create policy "Users upload own shelf images"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users update own shelf images" on storage.objects;
create policy "Users update own shelf images"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users delete own shelf images" on storage.objects;
create policy "Users delete own shelf images"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Admin audit log (service-role only)
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users (id) on delete set null,
  action text not null,
  target_user_id uuid references auth.users (id) on delete set null,
  meta jsonb not null default '{}'::jsonb,
  ip text,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log (created_at desc);
create index if not exists admin_audit_log_actor_idx
  on public.admin_audit_log (actor_user_id);
create index if not exists admin_audit_log_target_idx
  on public.admin_audit_log (target_user_id);

alter table public.admin_audit_log enable row level security;
revoke all on public.admin_audit_log from anon, authenticated;
grant select, insert on public.admin_audit_log to service_role;

create table if not exists public.admin_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.admin_settings enable row level security;
revoke all on public.admin_settings from anon, authenticated;
grant select, insert, update on public.admin_settings to service_role;

create table if not exists public.signup_events (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text,
  provider text,
  created_at timestamptz not null,
  recorded_at timestamptz not null default now(),
  immediate_notified_at timestamptz,
  digest_notified_at timestamptz
);

create index if not exists signup_events_created_at_idx
  on public.signup_events (created_at desc);

alter table public.signup_events enable row level security;
revoke all on public.signup_events from anon, authenticated;
grant select, insert, update on public.signup_events to service_role;

insert into public.admin_settings (key, value)
values ('signup_notify_mode', '{"mode":"immediate"}'::jsonb)
on conflict (key) do nothing;

-- Support tickets (service-role only)
create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  user_id uuid references auth.users (id) on delete set null,
  email text not null,
  category text not null
    check (category in ('billing', 'ocr', 'account', 'bug', 'other')),
  subject text not null,
  body text not null,
  status text not null default 'open'
    check (status in ('open', 'pending', 'resolved', 'closed')),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high')),
  meta jsonb not null default '{}'::jsonb,
  ai_suggestion text,
  ai_suggestion_status text not null default 'pending'
    check (ai_suggestion_status in ('pending', 'ready', 'failed', 'skipped')),
  ai_suggestion_generated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_tickets_status_created_idx
  on public.support_tickets (status, created_at desc);
create index if not exists support_tickets_user_id_idx
  on public.support_tickets (user_id);
create index if not exists support_tickets_email_idx
  on public.support_tickets (email);

create table if not exists public.support_ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets (id) on delete cascade,
  author_type text not null
    check (author_type in ('user', 'admin', 'system')),
  author_user_id uuid references auth.users (id) on delete set null,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists support_ticket_messages_ticket_idx
  on public.support_ticket_messages (ticket_id, created_at);

alter table public.support_tickets enable row level security;
alter table public.support_ticket_messages enable row level security;
revoke all on public.support_tickets from anon, authenticated;
revoke all on public.support_ticket_messages from anon, authenticated;
grant select, insert, update, delete on public.support_tickets to service_role;
grant select, insert, delete on public.support_ticket_messages to service_role;

insert into public.admin_settings (key, value)
values ('support_notify_mode', '{"mode":"immediate"}'::jsonb)
on conflict (key) do nothing;

-- Usage + engagement (service-role only)
create table if not exists public.api_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  action text not null
    check (action in (
      'ocr_ok',
      'ocr_error',
      'ocr_rate_limit',
      'books_ok',
      'books_rate_limit'
    )),
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists api_usage_events_action_created_idx
  on public.api_usage_events (action, created_at desc);
create index if not exists api_usage_events_user_created_idx
  on public.api_usage_events (user_id, created_at desc);

create table if not exists public.user_engagement (
  user_id uuid primary key references auth.users (id) on delete cascade,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  request_count bigint not null default 1
);

create index if not exists user_engagement_last_seen_idx
  on public.user_engagement (last_seen_at desc);

alter table public.api_usage_events enable row level security;
alter table public.user_engagement enable row level security;
revoke all on public.api_usage_events from anon, authenticated;
revoke all on public.user_engagement from anon, authenticated;
grant select, insert on public.api_usage_events to service_role;
grant select, insert, update on public.user_engagement to service_role;

drop function if exists public.hilibrary_has_column(text, text);

notify pgrst, 'reload schema';
