-- HiLibrary — migrate an existing (close) Supabase database
-- Safe to re-run. Adds missing tables/columns/indexes/RLS/storage.
-- Does not drop leftover columns (e.g. image_hash, cover_url after copy).

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

create or replace function public.hilibrary_has_column(tbl text, col text)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = tbl
      and column_name = col
  );
$$;

-- ---------------------------------------------------------------------------
-- Tables (create only if missing)
-- ---------------------------------------------------------------------------

create table if not exists public.libraries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  name text,
  created_at timestamptz default now()
);

create table if not exists public.shelves (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  library_id bigint,
  name text,
  image_url text not null,
  detected_spines jsonb,
  dismissed_titles jsonb,
  map_x double precision,
  map_y double precision,
  map_scale double precision,
  created_at timestamptz default now(),
  map_width integer
);

create table if not exists public.user_books (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  shelf_id bigint,
  title text,
  author text,
  cover text,
  shelf_image_url text,
  bounding_box jsonb,
  polygon jsonb,
  created_at timestamptz default now()
);

create table if not exists public.ocr_cache (
  hash text primary key,
  words jsonb not null default '[]'::jsonb,
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- shelves: add missing columns used by the app
-- ---------------------------------------------------------------------------

alter table public.shelves add column if not exists user_id uuid;
alter table public.shelves add column if not exists library_id bigint;
alter table public.shelves add column if not exists name text;
alter table public.shelves add column if not exists image_url text;
alter table public.shelves add column if not exists detected_spines jsonb;
alter table public.shelves add column if not exists dismissed_titles jsonb;
alter table public.shelves add column if not exists map_x double precision;
alter table public.shelves add column if not exists map_y double precision;
alter table public.shelves add column if not exists map_scale double precision;
alter table public.shelves add column if not exists created_at timestamptz default now();
alter table public.shelves add column if not exists map_width integer;

-- ---------------------------------------------------------------------------
-- user_books: cover_url -> cover, then add remaining columns
-- ---------------------------------------------------------------------------

do $$
begin
  if public.hilibrary_has_column('user_books', 'cover_url')
     and not public.hilibrary_has_column('user_books', 'cover') then
    alter table public.user_books rename column cover_url to cover;
  elsif public.hilibrary_has_column('user_books', 'cover_url')
        and public.hilibrary_has_column('user_books', 'cover') then
    update public.user_books
    set cover = cover_url
    where cover is null and cover_url is not null;
  end if;
end $$;

alter table public.user_books add column if not exists user_id uuid;
alter table public.user_books add column if not exists shelf_id bigint;
alter table public.user_books add column if not exists title text;
alter table public.user_books add column if not exists author text;
alter table public.user_books add column if not exists cover text;
alter table public.user_books add column if not exists shelf_image_url text;
alter table public.user_books add column if not exists bounding_box jsonb;
alter table public.user_books add column if not exists polygon jsonb;
alter table public.user_books add column if not exists created_at timestamptz default now();

alter table public.ocr_cache add column if not exists words jsonb;
alter table public.ocr_cache add column if not exists created_at timestamptz default now();
alter table public.libraries add column if not exists user_id uuid;
alter table public.libraries add column if not exists name text;
alter table public.libraries add column if not exists created_at timestamptz default now();

-- ---------------------------------------------------------------------------
-- Constraints / FKs (skip if they already exist)
-- ---------------------------------------------------------------------------

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'shelves_user_id_fkey'
  ) then
    alter table public.shelves
      add constraint shelves_user_id_fkey
      foreign key (user_id) references auth.users (id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'shelves_library_id_fkey'
  ) then
    alter table public.shelves
      add constraint shelves_library_id_fkey
      foreign key (library_id) references public.libraries (id) on delete set null;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'user_books_user_id_fkey'
  ) then
    alter table public.user_books
      add constraint user_books_user_id_fkey
      foreign key (user_id) references auth.users (id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'user_books_shelf_id_fkey'
  ) then
    alter table public.user_books
      add constraint user_books_shelf_id_fkey
      foreign key (shelf_id) references public.shelves (id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'libraries_user_id_fkey'
  ) then
    alter table public.libraries
      add constraint libraries_user_id_fkey
      foreign key (user_id) references auth.users (id) on delete cascade;
  end if;
end $$;

-- Unique image_url (required by the app). Fails if duplicates already exist.
create unique index if not exists shelves_image_url_key on public.shelves (image_url);

create index if not exists libraries_user_id_idx on public.libraries (user_id);
create index if not exists shelves_user_id_idx on public.shelves (user_id);
create index if not exists shelves_library_id_idx on public.shelves (library_id);
create index if not exists user_books_user_id_idx on public.user_books (user_id);
create index if not exists user_books_shelf_id_idx on public.user_books (shelf_id);

-- ---------------------------------------------------------------------------
-- Grants + RLS
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated, service_role;

grant select, insert, update, delete
  on public.libraries, public.shelves, public.user_books
  to authenticated;

grant all on public.libraries, public.shelves, public.user_books, public.ocr_cache
  to service_role;

revoke all on public.ocr_cache from anon, authenticated;

grant usage, select
  on all sequences in schema public
  to authenticated, service_role;

alter table public.libraries enable row level security;
alter table public.shelves enable row level security;
alter table public.user_books enable row level security;
alter table public.ocr_cache enable row level security;

drop policy if exists libraries_own_rows on public.libraries;
create policy libraries_own_rows
  on public.libraries
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists shelves_own_rows on public.shelves;
create policy shelves_own_rows
  on public.shelves
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists user_books_own_rows on public.user_books;
create policy user_books_own_rows
  on public.user_books
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and (
      shelf_id is null
      or exists (
        select 1
        from public.shelves s
        where s.id = shelf_id
          and s.user_id = auth.uid()
      )
    )
  );

-- ---------------------------------------------------------------------------
-- Storage bucket
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('shelves', 'shelves', false)
on conflict (id) do update
set public = false;

drop policy if exists "Public read shelf images" on storage.objects;
drop policy if exists "Users read own shelf images" on storage.objects;
create policy "Users read own shelf images"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users upload own shelf images" on storage.objects;
create policy "Users upload own shelf images"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users update own shelf images" on storage.objects;
create policy "Users update own shelf images"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users delete own shelf images" on storage.objects;
create policy "Users delete own shelf images"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop function if exists public.hilibrary_has_column(text, text);

notify pgrst, 'reload schema';
