-- ShelfMapper — Supabase schema (from scratch)
-- Paste into the Supabase SQL Editor and run.
-- Auth (auth.users) is created by Supabase; this script only adds app tables,
-- RLS, and the public `shelves` storage bucket.
--
-- To wipe an existing app schema first, uncomment:
-- drop table if exists public.user_books cascade;
-- drop table if exists public.shelves cascade;
-- drop table if exists public.libraries cascade;
-- drop table if exists public.ocr_cache cascade;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.libraries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  name text,
  created_at timestamptz default now()
);

create table if not exists public.shelves (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  library_id bigint references public.libraries (id) on delete set null,
  name text,
  image_url text not null unique,
  detected_spines jsonb,
  dismissed_titles jsonb,
  map_x double precision,
  map_y double precision,
  map_scale double precision,
  created_at timestamptz default now(),
  map_width integer
);

create table if not exists public.user_books (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  shelf_id bigint references public.shelves (id) on delete cascade,
  title text,
  author text,
  cover text,
  shelf_image_url text,
  bounding_box jsonb,
  polygon jsonb,
  created_at timestamptz default now()
);

-- Shared OCR cache. The API writes this with the service role key.
create table if not exists public.ocr_cache (
  hash text primary key,
  words jsonb not null default '[]'::jsonb,
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- Indexes (RLS filters + common lookups)
-- ---------------------------------------------------------------------------

create index if not exists libraries_user_id_idx on public.libraries (user_id);
create index if not exists shelves_user_id_idx on public.shelves (user_id);
create index if not exists shelves_library_id_idx on public.shelves (library_id);
create index if not exists user_books_user_id_idx on public.user_books (user_id);
create index if not exists user_books_shelf_id_idx on public.user_books (shelf_id);

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated, service_role;

grant select, insert, update, delete
  on public.libraries, public.shelves, public.user_books
  to authenticated;

grant all on public.libraries, public.shelves, public.user_books, public.ocr_cache
  to service_role;

revoke all on public.ocr_cache from anon, authenticated;

grant usage, select
  on all sequences in schema public
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.libraries enable row level security;
alter table public.shelves enable row level security;
alter table public.user_books enable row level security;
alter table public.ocr_cache enable row level security;

drop policy if exists libraries_own_rows on public.libraries;
create policy libraries_own_rows
  on public.libraries
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists shelves_own_rows on public.shelves;
create policy shelves_own_rows
  on public.shelves
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists user_books_own_rows on public.user_books;
create policy user_books_own_rows
  on public.user_books
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and (
      shelf_id is null
      or exists (
        select 1
        from public.shelves s
        where s.id = shelf_id
          and s.user_id = auth.uid()
      )
    )
  );

-- No authenticated/anon policies on ocr_cache: service_role bypasses RLS.

-- ---------------------------------------------------------------------------
-- Storage: private bucket for shelf photos
-- Client uploads to `{user_id}/{hash}.jpg`.
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('shelves', 'shelves', false)
on conflict (id) do update
set public = false;

drop policy if exists "Public read shelf images" on storage.objects;
drop policy if exists "Users read own shelf images" on storage.objects;
create policy "Users read own shelf images"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users upload own shelf images" on storage.objects;
create policy "Users upload own shelf images"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users update own shelf images" on storage.objects;
create policy "Users update own shelf images"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users delete own shelf images" on storage.objects;
create policy "Users delete own shelf images"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'shelves'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- ---------------------------------------------------------------------------
-- Admin audit (service-role only)
-- ---------------------------------------------------------------------------

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users (id) on delete set null,
  action text not null,
  target_user_id uuid references auth.users (id) on delete set null,
  meta jsonb not null default '{}'::jsonb,
  ip text,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log (created_at desc);
create index if not exists admin_audit_log_actor_idx
  on public.admin_audit_log (actor_user_id);
create index if not exists admin_audit_log_target_idx
  on public.admin_audit_log (target_user_id);

alter table public.admin_audit_log enable row level security;
revoke all on public.admin_audit_log from anon, authenticated;
grant select, insert on public.admin_audit_log to service_role;

notify pgrst, 'reload schema';
