-- Support tickets + thread messages (service-role only)
-- Safe to re-run.

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  user_id uuid references auth.users (id) on delete set null,
  email text not null,
  category text not null
    check (category in ('billing', 'ocr', 'account', 'bug', 'other')),
  subject text not null,
  body text not null,
  status text not null default 'open'
    check (status in ('open', 'pending', 'resolved', 'closed')),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high')),
  meta jsonb not null default '{}'::jsonb,
  ai_suggestion text,
  ai_suggestion_status text not null default 'pending'
    check (ai_suggestion_status in ('pending', 'ready', 'failed', 'skipped')),
  ai_suggestion_generated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_tickets_status_created_idx
  on public.support_tickets (status, created_at desc);

create index if not exists support_tickets_user_id_idx
  on public.support_tickets (user_id);

create index if not exists support_tickets_email_idx
  on public.support_tickets (email);

create table if not exists public.support_ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets (id) on delete cascade,
  author_type text not null
    check (author_type in ('user', 'admin', 'system')),
  author_user_id uuid references auth.users (id) on delete set null,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists support_ticket_messages_ticket_idx
  on public.support_ticket_messages (ticket_id, created_at);

alter table public.support_tickets enable row level security;
alter table public.support_ticket_messages enable row level security;

revoke all on public.support_tickets from anon, authenticated;
revoke all on public.support_ticket_messages from anon, authenticated;

grant select, insert, update, delete on public.support_tickets to service_role;
grant select, insert, delete on public.support_ticket_messages to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.admin_settings (key, value)
values ('support_notify_mode', '{"mode":"immediate"}'::jsonb)
on conflict (key) do nothing;
